#ifndef STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_DB_IMPL_H
#define STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_DB_IMPL_H

namespace simple_leveldb {

}

#endif//! STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_DB_IMPL_H
