#ifndef STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_POSIX_ENV_H
#define STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_POSIX_ENV_H

namespace simple_leveldb {


}

#endif//! STORAGE_SIMPEL_LEVELDB_INCLUDE_DETAIL_POSIX_ENV_H
